//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineerTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngineerTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 某公司 的本地化字符串。
        /// </summary>
        internal static string About_Product_Copyrights {
            get {
                return ResourceManager.GetString("About_Product_Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 某公司工程师助手 的本地化字符串。
        /// </summary>
        internal static string About_Product_Name {
            get {
                return ResourceManager.GetString("About_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V1.0.00 的本地化字符串。
        /// </summary>
        internal static string About_Product_Verson {
            get {
                return ResourceManager.GetString("About_Product_Verson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon AddDataSheet {
            get {
                object obj = ResourceManager.GetObject("AddDataSheet", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap AddDataSheetPNG {
            get {
                object obj = ResourceManager.GetObject("AddDataSheetPNG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap AddEquipPNG {
            get {
                object obj = ResourceManager.GetObject("AddEquipPNG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        internal static string HideMainNotifyIconStripMenuItem {
            get {
                return ResourceManager.GetString("HideMainNotifyIconStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认页 的本地化字符串。
        /// </summary>
        internal static string MainTab_Default {
            get {
                return ResourceManager.GetString("MainTab_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化工作空间 的本地化字符串。
        /// </summary>
        internal static string Menu_File_InitialWorkingSpace {
            get {
                return ResourceManager.GetString("Menu_File_InitialWorkingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存记录 的本地化字符串。
        /// </summary>
        internal static string MenuFileSaveLog {
            get {
                return ResourceManager.GetString("MenuFileSaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用说明 的本地化字符串。
        /// </summary>
        internal static string MenuHelpReadsMe {
            get {
                return ResourceManager.GetString("MenuHelpReadsMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        internal static string MenuProject {
            get {
                return ResourceManager.GetString("MenuProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项目 的本地化字符串。
        /// </summary>
        internal static string MenuProjectAdd {
            get {
                return ResourceManager.GetString("MenuProjectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string MenuToolsSetting {
            get {
                return ResourceManager.GetString("MenuToolsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string ShowMainNotifyIconStripMenuItem {
            get {
                return ResourceManager.GetString("ShowMainNotifyIconStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员 的本地化字符串。
        /// </summary>
        internal static string SourceTab_AllPerson {
            get {
                return ResourceManager.GetString("SourceTab_AllPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有项目 的本地化字符串。
        /// </summary>
        internal static string SourceTab_AllWork {
            get {
                return ResourceManager.GetString("SourceTab_AllWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的文件 的本地化字符串。
        /// </summary>
        internal static string SourceTab_MyFile {
            get {
                return ResourceManager.GetString("SourceTab_MyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的工作 的本地化字符串。
        /// </summary>
        internal static string SourceTab_MyWork {
            get {
                return ResourceManager.GetString("SourceTab_MyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能搜索 的本地化字符串。
        /// </summary>
        internal static string ToolStrip_SmartSearch {
            get {
                return ResourceManager.GetString("ToolStrip_SmartSearch", resourceCulture);
            }
        }
    }
}
